version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: boilerplate-postgres
    restart: always
    environment:
      POSTGRES_DB: boilerplate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senocak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./var/logs/postgresql:/var/log/postgresql
    ports:
      - "5433:5432"
    healthcheck:
      test: "pg_isready -U postgres"
    networks:
      - boilerplate
  redis:
    image: redis:7.0.5-alpine
    container_name: boilerplate-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass senocak
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - boilerplate
  backend:
    build:
      context: ./spring-kotlin17/auth
      dockerfile: Dockerfile
    container_name: boilerplate-spring-kotlin
    ports:
      - "8080:8080"
    restart: always
    environment:
      SERVER_PORT: 8080
      SERVER_IP: localhost
      POSTGRESQL_PORT: 5433
      POSTGRESQL_DB: boilerplate
      POSTGRESQL_SCHEMA: public
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: senocak
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: senocak
      REDIS_TIMEOUT: 300
    networks:
      - boilerplate
    depends_on:
      - postgres
      - redis
  #frontend:
  #  build:
  #    context: ./react-ts
  #    dockerfile: Dockerfile
  #  container_name: boilerplate-react-typescript
  #  ports:
  #    - "3232:3232"
  #  depends_on:
  #    - backend
  #  networks:
  #    - boilerplate
networks:
  boilerplate:
volumes:
  db-data:
  rabbitmq-data:
  redis-data:
  pgadmin-data:
  nginx-proxy-manager-data:
  letsencrypt-data:
  mysql-data:
  consul-data:
  minio_storage: {}