version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: postgres-boilerplate
    restart: always
    environment:
      POSTGRES_DB: boilerplate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senocak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./var/logs/postgresql:/var/log/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
    networks:
      - boilerplate
  redis:
    image: redis:7.0.5-alpine
    container_name: redis-boilerplate
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass senocak
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - boilerplate
  backend:
    build:
      context: ./spring-kotlin17/auth
      dockerfile: Dockerfile
    container_name: boilerplate-spring-kotlin
    ports:
      - "8080:8080"
    restart: no
    environment:
      SERVER_PORT: 8080
      SERVER_IP: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DB: boilerplate
      POSTGRESQL_SCHEMA: public
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: senocak

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: senocak
      REDIS_TIMEOUT: 300

      MAIL_HOST: smtp.yandex.com.tr
      MAIL_PROTOCOL: smtp
      MAIL_USERNAME: notification@cosmosboard.com
      MAIL_PASSWORD: xsqgbadvvwxasyoq

      APP_FRONTEND_URL: http://localhost:3232

    networks:
      - boilerplate
    depends_on:
      - postgres
      - redis
  frontend:
    build:
      context: ./react-ts
      dockerfile: Dockerfile
    container_name: boilerplate-react-typescript
    ports:
      - "3232:3232"
    depends_on:
      - backend
    networks:
      - boilerplate
networks:
  boilerplate:
volumes:
  db-data:
  redis-data: